---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ThodbergMisc

<!-- badges: start -->
<!-- badges: end -->

ThodbergMisc stores various things I use all the time:

- Useful and sorted collections of CRAN and Bioconductor packages.
- Template .Rprofile.
- A few useful Rstudio addins.
- Small useful R functions.

## Installation

`ThodbergMisc` will only live on github:
``` r
# install.packages("devtools")
devtools::install_github("MalteThodberg/ThodbergMisc")
```

To install all packages:

``` r
# Install installers
install.packages(c("devtools", "BiocManager"))

# Install from  github
devtools::install_github("maltethodberg/ThodbergMisc")

# Install all collections
install.packages(unlist(ThodbergMisc::package_collections))
BiocManager::install(unlist(ThodbergMisc::package_collections))
install.packages("tidyverse)
```
If you need the .Rprofile, look at `create_Rprofile`

## Package collections

```{r example}
library(ThodbergMisc)
package_collections
```
